.

diff --git a/.github/workflows/perform-lints.yml b/.github/workflows/perform-lints.yml
--- a/.github/workflows/perform-lints.yml
+++ b/.github/workflows/perform-lints.yml
@@ -392,10 +392,18 @@ jobs:
       
       - name: Debug schemas
         run: |
+          if [ ! -f /tmp/${{ steps.get-latest-tag.outputs.tag }}.graphql ]; then
+            echo "File not found!"
+            exit 1
+          else
+            echo "File exists."
+          fi
+
+          "Current schema:"
           cat /tmp/schema.graphql
-          echo "Previous schema"
+          echo "Previous schema:"
           cat /tmp/${{ steps.get-latest-tag.outputs.tag }}.graphql
-      
+
       # https://github.com/marketplace/actions/graphql-inspector
       - name: Install Schema Inspector
         run: |
